### ISSUE TITLE
Failed to find Ignition Gazebo ~=6.0.0.dev

### ISSUE THREAD

**Issue by dnovischi** [robotology/gym-ignition#423]
## Description:

Running the example for ScenarIO form the docs in [1] fails:

```
Traceback (most recent call last):
  File "/home/dan/workspace/mrsrl_ws/test/main.py", line 3, in <module>
    from scenario import gazebo as scenario_gazebo
  File "/home/dan/anaconda3/envs/mrsrl/lib/python3.8/site-packages/scenario/__init__.py", line 227, in <module>
    check_gazebo_installation()
  File "/home/dan/anaconda3/envs/mrsrl/lib/python3.8/site-packages/scenario/__init__.py", line 175, in check_gazebo_installation
    raise RuntimeError(msg)
RuntimeError: Failed to find Ignition Gazebo ~=6.0.0.dev (found incompatible version(s): [<Version('6.1.0')>, <Version('5.2.0')>, <Version('4.12.0')>, <Version('3.12.0')>])
```

[1][https://robotology.github.io/gym-ignition/master/getting_started/scenario.html#python](https://robotology.github.io/gym-ignition/master/getting_started/scenario.html#python)

## Steps to reproduce

1. `sudo apt install ignition-*`
1. `pip install gym-ignition`
1. `python example.py`

## Environment

- OS: <Ubuntu 20.04 Focal>
- GPU: <NVidia 1050Ti>    
- Python: <3.8.X from conda environment -->
- Version: 
- Channel:
  - [x] Stable
- Installation type:
  - [x] User
  - [ ] Developer
- Conda environment packages:
 ```
conda list
# packages in environment at ../anaconda3/envs/mrsrl:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
absl-py                   0.15.0             pyhd8ed1ab_0    conda-forge
aiohttp                   3.7.4.post0      py38h497a2fe_0    conda-forge
anyio                     3.3.4            py38h578d9bd_1    conda-forge
argon2-cffi               20.1.0           py38h27cfd23_1  
async-timeout             3.0.1            py38h06a4308_0  
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
blinker                   1.4                        py_1    conda-forge
brotli                    1.0.9                h7f98852_5    conda-forge
brotli-bin                1.0.9                h7f98852_5    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.17.1               h27cfd23_0  
ca-certificates           2021.10.8            ha878542_0    conda-forge
cachetools                4.2.4              pyhd8ed1ab_0    conda-forge
certifi                   2021.10.8        py38h578d9bd_1    conda-forge
cffi                      1.14.5           py38h261ae71_0  
chardet                   4.0.0            py38h578d9bd_2    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
click                     8.0.3            py38h578d9bd_1    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              35.0.0           py38ha5dfef3_0    conda-forge
cudatoolkit               11.3.1               h2bc3f7f_2  
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
dbus                      1.13.18              hb2f20db_0  
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.4.1                h9c3ff4c_0    conda-forge
ffmpeg                    4.3                  hf484d3e_0    pytorch
fontconfig                2.13.1            hba837de_1005    conda-forge
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.11.0               h70c0345_0  
future                    0.18.2           py38h578d9bd_4    conda-forge
giflib                    5.2.1                h7b6447c_0  
glib                      2.69.1               h5202010_0  
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
google-auth               2.3.3              pyh6c4a22f_0    conda-forge
google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
grpcio                    1.37.1           py38hdd6454d_0    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               h28cd5cc_2  
gym                       0.21.0           py38he5a9106_0    conda-forge
gym-ignition              1.3.1                    pypi_0    pypi
gym-ignition-models       1.1.1                    pypi_0    pypi
icu                       58.2              hf484d3e_1000    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
idyntree                  4.2.0                    pypi_0    pypi
importlib-metadata        4.8.2            py38h578d9bd_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2021.4.0          h06a4308_3561  
ipykernel                 5.5.5            py38hd0cf306_0    conda-forge
ipython                   7.29.0           py38he5a9106_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.0           py38h578d9bd_3    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
joblib                    0.17.0                     py_0    anaconda
jpeg                      9d                   h7f8727e_0  
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.2.1              pyhd8ed1ab_0    conda-forge
jupyter_client            7.0.6              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1            py38h578d9bd_1    conda-forge
jupyter_server            1.11.2             pyhd8ed1ab_0    conda-forge
jupyterlab                3.2.3              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.8.2              pyhd8ed1ab_0    conda-forge
kiwisolver                1.3.1            py38h2531618_0  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libbrotlicommon           1.0.9                h7f98852_5    conda-forge
libbrotlidec              1.0.9                h7f98852_5    conda-forge
libbrotlienc              1.0.9                h7f98852_5    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libgomp                   9.3.0               h5101ec6_17  
libiconv                  1.15                 h63c8f33_5  
libidn2                   2.3.2                h7f8727e_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.15.8               h780b84a_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.2.0                h85742a9_0  
libunistring              0.9.10               h27cfd23_0  
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.40.0               h7b6447c_0  
libwebp                   1.2.0                h89dd481_0  
libwebp-base              1.2.0                h27cfd23_0  
libxcb                    1.13              h7f98852_1003    conda-forge
libxml2                   2.9.12               h03d6c58_0  
lxml                      4.6.4                    pypi_0    pypi
lz4-c                     1.9.3                h295c915_1  
markdown                  3.3.4              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py38h497a2fe_0    conda-forge
matplotlib                3.4.3            py38h578d9bd_1    conda-forge
matplotlib-base           3.4.3            py38hbbc1b5f_0  
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py38h497a2fe_1004    conda-forge
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py38h7f8727e_0  
mkl_fft                   1.3.1            py38hd3c417c_0  
mkl_random                1.2.2            py38h51133e4_0  
multidict                 5.1.0            py38h27cfd23_2  
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclassic                 0.3.4              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.8              pyhd8ed1ab_0    conda-forge
nbconvert                 6.3.0            py38h578d9bd_1    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h7f8727e_2  
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
nettle                    3.7.3                hbbd107a_1  
notebook                  6.4.5              pyha770c72_0    conda-forge
numpy                     1.21.2           py38h20f2e39_0  
numpy-base                1.21.2           py38h79a1101_0  
oauthlib                  3.1.1              pyhd8ed1ab_0    conda-forge
olefile                   0.46               pyhd3eb1b0_0  
openh264                  2.1.0                hd408876_0  
openssl                   1.1.1l               h7f8727e_0  
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandas                    1.1.3            py38he6710b0_0    anaconda
pandoc                    2.16.1               h7f98852_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0            py38h5aabda8_0  
pip                       21.2.4           py38h06a4308_0  
prometheus_client         0.12.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.22             pyha770c72_0    conda-forge
protobuf                  3.15.8           py38h709712a_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyglet                    1.5.16           py38h578d9bd_0    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.3.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pyqt                      5.9.2            py38h05f1152_4  
pyrsistent                0.18.0           py38heee7806_0  
pysocks                   1.7.1            py38h578d9bd_4    conda-forge
python                    3.8.12               h12debd9_0  
python-dateutil           2.8.1                      py_0    anaconda
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.10.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2020.1                     py_0    anaconda
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pyzmq                     19.0.2           py38ha71036d_2    conda-forge
qt                        5.9.7                h5867ecd_1  
readline                  8.1                  h27cfd23_0  
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
rsa                       4.7.2              pyh44b312d_0    conda-forge
scenario                  1.3.1                    pypi_0    pypi
scikit-learn              0.23.2           py38h0573a6f_0    anaconda
scipy                     1.6.2            py38had2a1c9_1  
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                58.0.4           py38h06a4308_0  
sip                       4.19.13          py38he6710b0_0  
six                       1.16.0             pyhd3eb1b0_0  
sniffio                   1.2.0            py38h578d9bd_2    conda-forge
sqlite                    3.36.0               hc218d9a_0  
tensorboard               2.7.0              pyhd8ed1ab_0    conda-forge
tensorboard-data-server   0.6.0            py38h2b97feb_0    conda-forge
tensorboard-plugin-wit    1.8.0              pyh44b312d_0    conda-forge
terminado                 0.12.1           py38h578d9bd_1    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    anaconda
tk                        8.6.11               h1ccaba5_0  
torchaudio                0.10.0               py38_cu113    pytorch
torchvision               0.11.1               py38_cu113    pytorch
tornado                   6.1              py38h497a2fe_1    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typing-extensions         3.10.0.2             hd3eb1b0_0  
typing_extensions         3.10.0.2           pyh06a4308_0  
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.1.0            py38h578d9bd_1    conda-forge
werkzeug                  2.0.1              pyhd8ed1ab_0    conda-forge
wheel                     0.37.0             pyhd3eb1b0_1  
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h7b6447c_0  
yarl                      1.6.3            py38h497a2fe_2    conda-forge
zeromq                    4.3.4                h9c3ff4c_0    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0  
```

**Comment by diegoferigo** [comment]
Hi @dnovischi, we are aware that `master` only supports the 6.0 version, while the last Ignition Gazebo release is 6.1[^1]. 

Waiting for a new release, you can install the project from its Nightly channel.

[^1]: https://github.com/robotology/gym-ignition/discussions/414#discussioncomment-1597672

**Comment by diegoferigo** [comment]
I noted that you used conda to install the dependencies. We are in the process to package this project in conda-forge, if you're interested you can follow https://github.com/conda-forge/staged-recipes/pull/16582.

**Comment by dnovischi** [comment]
Thanks.

**Comment by diegoferigo** [comment]
I'll keep this issue open so that it has visibility in case other users try to install the Stable channel with the most recent Ignition Gazebo. I'll close it as soon as a new release will be rolled out.

**Comment by dnovischi** [comment]
That's probably for the best until migration. I can confirm that it works with nightly.

**Comment by psh9002** [comment]
When I tried install with the Nightly version, there was `TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases` which is started from `gym_ignition_environments`.

How can I fix it?
